Feat/official journal db
DMR-is/dmr.is pull request #85
Opened 2024-04-30 15:46 UTC by Tryggvig

First version of sequelize db with service

2024-04-30 15:50 UTC, jonbjarnio commented on departments.sql
Er þetta á réttum stað?

2024-04-30 16:00 UTC, jonbjarnio requested changes

2024-04-30 16:00 UTC, jonbjarnio commented on package.json
> +    "next": "14.0.4",
Uppfærsla á next?

2024-04-30 16:01 UTC, Tryggvig commented on apps/official-journal-api-export-e2e/project.json
jebb

2024-04-30 16:04 UTC, Tryggvig commented on libs/shared/modules/src/journal/journal.service.ts
NEVAH

2024-04-30 16:06 UTC, jonbjarnio approved these changes
LGTM 🤝

2024-04-30 16:06 UTC, merged

2025-03-11 14:43 UTC, DMR-Account commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/DMR-is/dmr.is/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: